version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curveball_app
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - .env
