version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curveball_app
    restart: always
    ports:
      - "4002:4002"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: curveball_redis
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
