export enum ErrorCode {
    // User
    USER_ALREADY_FLAGGED = 'USER_ALREADY_FLAGGED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_CLAIMED_TEAM = 'USER_ALREADY_CLAIMED_TEAM',
    USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',

    // Team
    TEAM_ALREADY_CLAIMED = 'TEAM_ALREADY_CLAIMED',
    TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',

    // Email
    EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
    EMAIL_NOT_VALID = 'EMAIL_NOT_VALID',

    // Username
    USERNAME_ALREADY_USED = 'USERNAME_ALREADY_USED',
    USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
    USERNAME_TOO_LONG = 'USERNAME_TOO_LONG',
    USERNAME_NOT_VALID = 'USERNAME_NOT_VALID',

    // Password
    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
    PASSWORD_NOT_VALID = 'PASSWORD_NOT_VALID',

    // Token
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',

    // Review
    REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
    ALREADY_FLAGGED_REVIEW = 'ALREADY_FLAGGED_REVIEW',

    // Flag
    REASON_REQUIRED = 'REASON_REQUIRED',
    REVIEW_ID_REQUIRED = 'REVIEW_ID_REQUIRED',
    FLAG_NOT_FOUND = 'FLAG_NOT_FOUND',
    INVALID_FLAG_STATUS = 'INVALID_STATUS',

    //   Admin
    CANNOT_BAN_SELF = 'CANNOT_BAN_SELF',

    // Auth
    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',

    ORGANIZATION_NOT_FOUND='ORGANIZATION_NOT_FOUND',
    ORGANIZATION_ALREADY_HAS_ACTIVE_SUBSCRIPTION = 'ORGANIZATION_ALREADY_HAS_ACTIVE_SUBSCRIPTION',
}
