export enum ErrorCode {
    USER_ALREADY_FLAGGED = 'USER_ALREADY_FLAGGED',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    USER_ALREADY_CLAIMED_TEAM = 'USER_ALREADY_CLAIMED_TEAM',
    USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',

    TEAM_ALREADY_CLAIMED = 'TEAM_ALREADY_CLAIMED',
    TEAM_NOT_FOUND = 'TEAM_NOT_FOUND',

    EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
    EMAIL_NOT_VALID = 'EMAIL_NOT_VALID',

    USERNAME_ALREADY_USED = 'USERNAME_ALREADY_USED',
    USERNAME_TOO_SHORT = 'USERNAME_TOO_SHORT',
    USERNAME_TOO_LONG = 'USERNAME_TOO_LONG',
    USERNAME_NOT_VALID = 'USERNAME_NOT_VALID',

    PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
    PASSWORD_NOT_VALID = 'PASSWORD_NOT_VALID',

    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',

    REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
    ALREADY_FLAGGED_REVIEW = 'ALREADY_FLAGGED_REVIEW',

    REASON_REQUIRED = 'REASON_REQUIRED',
    REVIEW_ID_REQUIRED = 'REVIEW_ID_REQUIRED',
    FLAG_NOT_FOUND = 'FLAG_NOT_FOUND',
    INVALID_FLAG_STATUS = 'INVALID_STATUS',

    CANNOT_BAN_SELF = 'CANNOT_BAN_SELF',

    EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
    INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',

    ORGANIZATION_NOT_FOUND='ORGANIZATION_NOT_FOUND',
    ORGANIZATION_ALREADY_HAS_ACTIVE_SUBSCRIPTION = 'ORGANIZATION_ALREADY_HAS_ACTIVE_SUBSCRIPTION',
    PLAN_NOT_SUPPORTED = 'PLAN_NOT_SUPPORTED',
    RESPONSE_NOT_FOUND = 'RESPONSE_NOT_FOUND',
    USER_NOT_AUTHORIZED = 'USER_NOT_AUTHORIZED',
    INVALID_PLAN_OR_STRIPE_PRICE = 'INVALID_PLAN_OR_STRIPE_PRICE',
    SOMETHING_WENT_WRONG = 'SOMETHING_WENT_WRONG',
    ACCESS_FORBIDDEN = 'ACCESS_FORBIDDEN',
    TOO_MANY_PHOTOS_UPLOADED_MAX_5 = 'TOO_MANY_PHOTOS_UPLOADED_MAX_5',
    ONLY_IMAGE_FILES_ALLOWED = 'ONLY_IMAGE_FILES_ALLOWED',
    EACH_FILE_SIZE_SHOULD_BE_UNDER_2MB='EACH_FILE_SIZE_SHOULD_BE_UNDER_2MB',
    TEAM_NOT_APPROVED='TEAM_NOT_APPROVED',
    USER_BANNED='USER_BANNED',
    TRYOUT_NOT_FOUND='TRYOUT_NOT_FOUND',
    NO_FILE_UPLOADED='NO_FILE_UPLOADED',
    INVALID_TARGET_ID='INVALID_TARGET_ID',
    CHECKOUT_SESSION_NOT_FOUND='CHECKOUT_SESSION_NOT_FOUND',
    PLAN_ALREADY_ACTIVE='PLAN_ALREADY_ACTIVE',
}
